### ISSUE TITLE
procamlib doesn't run

### ISSUE THREAD

**Issue by teganscott** [bytedeco/procamcalib#16] opened 2018-02-07 15:51 UTC
When trying to run "procamlib-nativelook" I get this error: java.lang.Exception: java.lang.NoClassDefFoundError: javax/activation/DataContentHandlerFactory

Running on OSX. 
Can the PS3 eye camera only run on Windows for this calibration?

Thanks for your help,
Tegan

**Comment by saudet** [comment] 2018-02-07 23:16
It should work, yes, but Java 9 isn't supported. Please try with Java 8.

**Comment by teganscott** [comment] 2018-02-08 03:55
Thank you, I ended up getting it to work on Windows, but will try this for the future

I've been trying for the past 6 hours to calibrate the system. I've only seen it flash twice in that time to capture an image. It finds both the projected and printed markers but rarely ever settles on an image. This was on a logitech webcam, now I am using the PS3 Eye and am having similar problems. If you have any suggestions it would be much appreciated.

**Comment by saudet** [comment] 2018-02-08 03:58
Nothing in particular other than adjusting the settings of ProCamCalib, your camera, and of your projector, as per the README.md file:
> When you want ProCamCalib to take an image for calibration, keep the board as steady as possible for a few seconds until you see the camera image "flash". Please refer to my Procams 2009 paper and the demo video to understand further how to perform calibration. Also, please note that ProCamCalib may fail to detect markers properly if they are not clear or big enough. Please adjust properly the focus, exposure, resolution, etc. of your projectors and cameras.

**Comment by saudet** [comment] 2018-02-08 03:59
Marking as duplicate of issue #15.

**Closed as completed by saudet** 2018-02-08 03:59 UTC
Labels: duplicate, enhancement
